local L = Rock("LibRockLocale-1.0"):GetTranslationNamespace("Cartographer_QuestInfo")

L:AddTranslations("enUS", function() return {

-- Core.lua
	["Export"] = true,
	["Export quest data to other addon."] = true,
	["Quests"] = true,
	["Export quest data to Cartographer Quests."] = true,
	["Export data"] = true,
	["Export quest data, this will take huge space."] = true,
	["Clear exported data"] = true,
	["Clear exported data."] = true,
	["Quest Objectives"] = true,
	["Export quest data to Cartographer QuestObjectives."] = true,
	["Icon alpha"] = true,
	["Alpha transparency of the icon."] = true,
	["Icon size"] = true,
	["Size of the icons on the map."] = true,
	["Show minimap icons"] = true,
	["Show quest icons on the minimap."] = true,
	["Show world map button"] = true,
	["Show button on the world map."] = true,
	["Show quest level"] = true,
	["Show quest level in quest log and NPC dialog."] = true,
	["Make quest log double wide"] = true,
	["Make the quest log window double wide, this will require UI reload."] = true,
	["Quest Info"] = true,
	["Module description"] = "Quest library for mob location and other information",
	["Exporting %d quest givers..."] = true,
	["Total %d quest givers have been exported."] = true,
	["Clear old exported quest givers first."] = true,
	["Begin exporting new quest givers."] = true,
	["Exporting %d quest objects..."] = true,
	["Total %d quest objects have been exported."] = true,
	["Clear old exported objectives first."] = true,
	["Begin exporting new quest objectives."] = true,
	["GROUP"] = GROUP,

-- LocationFrame.lua
	["Close"] = true,

-- Map.lua
	["Quest Start"] = true,
	["Quest End"] = true,
	["Quest Giver"] = true,
	["Quest Objective"] = true,
	["Show active quests"] = true,
	["Show all info of active quests in current map."] = true,
	["Show available quests"] = true,
	["Show the givers of available quests in current map."] = true,
	["Clear quest icons"] = true,
	["Clear quest icons generated by QuestInfo"] = true,
	["Open QuestInfo menu"] = true,
	["Alt-Click: "] = true,
	["Shift-Click: "] = true,
	["Elite"] = true,
	["Rare Elite"] = true,
	["Boss"] = true,
	["Name:"] = true,
	["Objective:"] = true,
	["Source:"] = true,
	["Level:"] = true,
	["Location:"] = true,
	["Quests:"] = true,
	["%d Quests"] = true,

-- QuestFuPatch.lua
	["(done)"] = true,

-- QuestLogPatch.lua
	[" ..."] = true,
	["... more"] = true,

-- SeriesFrame.lua
	["Quest Series"] = true,
	["Requires:"] = true,
	["Sharable"] = true,
	["Series:"] = true,

} end)
