--------------------------------------------------
-- localization.lua (chinese traditinal)
--------------------------------------------------
if ( GetLocale() == "zhTW" ) then
CHATBAR_SAY_ABRV		= "說";
CHATBAR_YELL_ABRV		= "喊";
CHATBAR_PARTY_ABRV		= "隊";
CHATBAR_RAID_ABRV		= "團";
CHATBAR_RAID_WARNING_ABRV	= "警";
CHATBAR_BATTLEGROUND_ABRV	= "戰";
CHATBAR_GUILD_ABRV		= "會";
CHATBAR_OFFICER_ABRV	= "官";
CHATBAR_WHISPER_ABRV	= "密";
CHATBAR_EMOTE_ABRV		= "表";

CHATBAR_MENU_MAIN_TITLE 			= "ChatBar 選項";
CHATBAR_MENU_MAIN_VERTICAL 			= "垂直方向";
CHATBAR_MENU_MAIN_REVERSE 			= "顛倒按鈕方向";
CHATBAR_MENU_MAIN_ALTART 			= "使用Alternate Artwork(換膚)";
CHATBAR_MENU_MAIN_TEXTONBUTTONS	 	= "文本在按鈕上";
CHATBAR_MENU_MAIN_SHOWTEXT 			= "顯示按鈕文本";
CHATBAR_MENU_MAIN_CHANNELID 		= "在按鈕上使用頻道ID";
CHATBAR_MENU_MAIN_BUTTONFLASHING	= "按鈕資訊閃爍";
CHATBAR_MENU_MAIN_BARBORDER 		= "顯示條邊框";
CHATBAR_MENU_MAIN_ADDONCHANNELS 	= "隱藏外掛程式頻道";
CHATBAR_MENU_MAIN_HIDEALL			= "隱藏所有按鈕";
CHATBAR_MENU_MAIN_HIDDENBUTTONS		= "隱藏按鈕";
CHATBAR_MENU_MAIN_RESET			 	= "重置位置";
CHATBAR_MENU_MAIN_REORDER			= "重置頻道";
CHATBAR_MENU_MAIN_REQCHRONOS			= "恢復常用頻道";

CHATBAR_MENU_CHANNEL_LEAVE			= "離開";
CHATBAR_MENU_CHANNEL_LIST			= "顯示頻道使用者清單";
CHATBAR_MENU_HIDE_BUTTON			= "隱藏 \"%s\" 按鈕";
CHATBAR_MENU_WHISPER_REPLY			= "回復";
CHATBAR_MENU_WHISPER_RETELL			= "重講";
CHATBAR_MENU_CHANNEL_STICKY			= "依附頻道";
CHATBAR_MENU_STICKY					= "依附";

CHATBAR_MENU_SHOW_BUTTON			= "顯示 \"%s\" 按鈕";

CHATBAR_REORDER_START = "頻道正被重置...";
CHATBAR_REORDER_END = "頻道重置完成。";
CHATBAR_REORDER_FLIGHT_FAIL = "當飛行的時候你不能重置頻道。";

-- Capital Cities
CHATBAR_SHATRATH		= "撒塔斯城";
CHATBAR_EXODAR			= "埃索達";
CHATBAR_SILVERMOON		= "銀月城";
CHATBAR_DALARAN			= "達拉然";
CHATBAR_ORGRIMMAR		= "奧格瑪";
CHATBAR_STORMWIND		= "暴風城";
CHATBAR_IRONFORGE		= "鐵爐堡";
CHATBAR_DARNASSUS		= "達納蘇斯";
CHATBAR_UNDERCITY		= "地下城";
CHATBAR_THUNDERBLUFF		= "雷霆崖";

CHATBAR_GENERAL				= "綜合";
CHATBAR_TRADE				= "交易";
CHATBAR_LFG					= "尋求組隊";
CHATBAR_LOCALDEFENSE		= "本地防務";
CHATBAR_WORLDDEFENSE		= "世界防務";
CHATBAR_GUILDRECRUITMENT	= "公會招寡";
end